// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyM-fLt2FH8eVr_Tqzfx4k72fDfWQCpVM',
    appId: '1:982502210200:web:535075b98c373fd601eeed',
    messagingSenderId: '982502210200',
    projectId: 'crudtutorial-e2ab0',
    authDomain: 'crudtutorial-e2ab0.firebaseapp.com',
    storageBucket: 'crudtutorial-e2ab0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAI0VN4YqbB_PW2aNC-5bIHkhYtEtFiG5k',
    appId: '1:982502210200:android:9c064e8d18c4d9b301eeed',
    messagingSenderId: '982502210200',
    projectId: 'crudtutorial-e2ab0',
    storageBucket: 'crudtutorial-e2ab0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHYbGI5hq991Xls2SryiJ1inY9Fav8Bic',
    appId: '1:982502210200:ios:2748a59b7e68598c01eeed',
    messagingSenderId: '982502210200',
    projectId: 'crudtutorial-e2ab0',
    storageBucket: 'crudtutorial-e2ab0.appspot.com',
    iosBundleId: 'com.example.crudtutorial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHYbGI5hq991Xls2SryiJ1inY9Fav8Bic',
    appId: '1:982502210200:ios:2748a59b7e68598c01eeed',
    messagingSenderId: '982502210200',
    projectId: 'crudtutorial-e2ab0',
    storageBucket: 'crudtutorial-e2ab0.appspot.com',
    iosBundleId: 'com.example.crudtutorial',
  );
}
